apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>My Custom Nginx Page</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          display: flex;
          justify-content: center;
          align-items: center;
          height: 100vh;
          margin: 0;
          background-color: #f0f0f0;
        }
        .container {
          text-align: center;
          padding: 2rem;
          background-color: #fff;
          border-radius: 10px;
          box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
        h1 {
          color: #333;
          font-size: 2.5rem;
          margin-bottom: 0.5rem;
        }
        p {
          color: #666;
          font-size: 1.2rem;
        }
        .button {
          display: inline-block;
          padding: 0.5rem 1.5rem;
          margin-top: 1rem;
          font-size: 1rem;
          color: #fff;
          background-color: #4CAF50;
          border: none;
          border-radius: 5px;
          text-decoration: none;
          cursor: pointer;
        }
        .button:hover {
          background-color: #45a049;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Welcome to My Custom Nginx Page!</h1>
        <p>This page is served by Nginx, customized with Kubernetes ConfigMap.</p>
        <a href="https://www.example.com" class="button">Learn More</a>
      </div>
    </body>
    </html>
