apiVersion: v1
data:
  config.html: |-
    <html>
    <head>
        <title>Config</title>
    </head>
    <body>
        <h1>Welcome to Config v1.1</h1>
    </body>
    </html>
  config1.html: |-
    <html>
    <head>
        <title>Config 1</title>
    </head>
    <body>
        <h1>Welcome to Config 1</h1>
    </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-html-config
  namespace: nginx-app